### ISSUE TITLE
MongoDB ID field issue

### ISSUE THREAD

**Issue by daeteck** [iiian/prisma-case#59]
Hi, 

I found this same issue in the library `https://github.com/loop-payments/prisma-lint` and that's why I tried this one for case linting of tables and field for a model of MongoDB in Prisma.

The issue is the following:

In MongoDB the id field is not Snake or Pascal case. The `id` is named by convention `_id`.

Example in Prisma Documentation:

https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/creating-the-prisma-schema-typescript-mongodb

```
model Post {
  id       String    @id @default(auto()) @map("_id") @db.ObjectId
  slug     String    @unique
  title    String
  body     String
  author   User      @relation(fields: [authorId], references: [id])
  authorId String    @db.ObjectId
  comments Comment[]
}
``` 

So the issue is that the `prisma-case-format` is removing the `@map("_id")` from the Prisma schema, when the idea is to keep that special mapping from `id` to `_id`.

This is a general rule and not something that should be added as an override table by table.

Thanks!

**Comment by iiian** [comment]
So essentially, if `provider = "mongodb"` then `id` shall map to `_id`

**Comment by daeteck** [comment]
> So essentially, if `provider = "mongodb"` then `id` shall map to `_id`

Yes, that's correct.

Give the option to omit some specific field without link that field to a table should be the way to go. Something like:

```yaml
default: ...
override:
  mYTaBlE: 'disable' # skip convention management for this table
  ...
  YourTable:
    default: '...'
    field:
      unmanaged_property: 'disable' # skip convention management for this field
override-field:
  id: 'disable'
``` 

Or if that is too hard perhaps another solution is to add the option of adding a comment to disable from the process the next line after a special comment, like the linting tools have. Something like:

```
model Post {
  // prisma-case-format-disable-next-line
  id       String    @id @default(auto()) @map("_id") @db.ObjectId
  slug     String    @unique
  title    String
  body     String
  author   User      @relation(fields: [authorId], references: [id])
  authorId String    @db.ObjectId
  comments Comment[]
}
```
